version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: gestor_restaurante_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: gestor_restaurante
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestor_restaurante_app
    restart: always
    ports:
      - "3006:3006"
    depends_on:
      - mongodb
    environment:
      PORT: 3006
      NODE_ENV: development
      URI_MONGO: mongodb://mongodb:27017/gestor_restaurante
      JWT_SECRET: clave_secreta_gestor_restaurante_2025
      JWT_EXPIRES_IN: 30m
      JWT_ISSUER: GestorRestaurante
      JWT_AUDIENCE: GestorRestauranteApp
    command: ["pnpm", "start"]

volumes:
  mongo_data:
